version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      RAILS_MAX_THREADS: 5
      # Environment variables for database configuration
      DATABASE_URL: "postgresql://dev:dev@db/dev"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - "5432:5432"

volumes:
  postgres-data: